language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="export CC=gcc-7 && CXX=g++-7"
    - LINKER_FLAGS=""

before_script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
